In [1]:
import pandas as pd

In [26]:
ids = [1161.0,
1139.0,
1320.0,
2110.0,
2305.0,
1032.0]
ids1 = [1413.0,
2325.0,
1009.0,
1411.0,
2429.0,
1268.0,
1218.0]
columns = ["pcl3", "intrusion", "avoidance", "hypertention", "ID"]

In [27]:
df = pd.read_excel(r"C:\Users\nogag\Documents\birocracy\PTSDClassifier\PTSD\Data\2009\questionnaires\questionnaire6PCL3.xlsx")

In [28]:
df1 = pd.read_excel(r"C:\Users\nogag\Documents\birocracy\PTSDClassifier\PTSD\Data\2009\PTSD.xlsx")

In [29]:
df1[df1["ID"].isin(ids)][["ID","phq3"]]

       ID   phq3
31   1032   6.75
138  1139  23.00
160  1161   5.00
317  1320  26.00
584  2110   0.00
777  2305   8.00

In [30]:
df[df["ID"].isin(ids)]

,ID,q6.1_INTRU,q6.2_DREAM,q6.3_FLASH,q6.4_UPSET,q6.5_PHYS,q6.6_AVTHT,q6.7_AVSIT,q6.8_AMNES,q6.9_DISINT,...,q6.14_ANGER,q6.15_CONC,q6.16_HYPER,q6.17_STRTL,pcl3,intrusion,avoidance,hypertention,PCL3_Broad,PCL3_Strict
22,1032,2.0,2.0,2.0,3.0,1.0,2.0,NaN,1.0,1.0,...,2.0,3.0,3.0,1.0,28.69,1,0,2,0,0
92,1139,2.0,2.0,2.0,2.0,1.0,1.0,1.0,3.0,2.0,...,2.0,2.0,2.0,2.0,32.00,0,2,0,0,0
107,1161,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,2.0,1.0,1.0,18.00,0,0,0,0,0
201,1320,3.0,3.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,...,5.0,5.0,5.0,5.0,55.00,1,2,6,0,0
363,2110,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.00,0,0,0,0,0
488,2305,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.00,0,0,0,0,0

In [31]:
df[df["ID"].isin(ids)][columns]

      pcl3  intrusion  avoidance  hypertention    ID
22   28.69          1          0             2  1032
92   32.00          0          2             0  1139
107  18.00          0          0             0  1161
201  55.00          1          2             6  1320
363  17.00          0          0             0  2110
488  17.00          0          0             0  2305

In [12]:
df[df["pcl3"] == 17]

,ID,q6.1_INTRU,q6.2_DREAM,q6.3_FLASH,q6.4_UPSET,q6.5_PHYS,q6.6_AVTHT,q6.7_AVSIT,q6.8_AMNES,q6.9_DISINT,...,q6.14_ANGER,q6.15_CONC,q6.16_HYPER,q6.17_STRTL,pcl3,intrusion,avoidance,hypertention,PCL3_Broad,PCL3_Strict
3,1004,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
13,1015,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
14,1017,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
16,1021,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
21,1030,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,8423,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
709,8809,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
717,8888,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
721,9002,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0
723,9006,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,17.0,0,0,0,0,0